def getBranchName() {
    return env.BRANCH_NAME.replace('origin/', '')
}

def getPort(branchName) {
    def portMapping = '5051:5000' // Default for feature branches

    if (branchName == 'main') {
        portMapping = '5000:5000'
    } else if (branchName == 'staging') {
        portMapping = '5050:5000'
    }

    return portMapping             
}

pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'devops'
    }

    parameters {
        choice(name: 'DEPLOY_ENV', choices: ['dev', 'stage', 'prod'], description: 'Select environment')
    }

    stages {
        stage('Load Config') {
            steps {
                script {
                    echo "Read properties from: ${params.DEPLOY_ENV}"

                    def config = "jenkins/config/${params.DEPLOY_ENV}.properties"
                    def props = readProperties file: config

                    env.PORT_MAPPING = props.PORT_MAPPING
                    
                    echo "PORT of ${params.DEPLOY_ENV} : ${props.PORT_MAPPING}"
                }
            }
        }

        stage('Run in Stage Only') {
            when {
                branch 'staging'
            }
            steps {
                echo "Running in stage only..."
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
                echo 'Checking out the code...'
            }
        }

        stage('Build') {
            steps {
                script {
                    sh 'dotnet restore'
                    sh 'dotnet build --configuration Release -p:Version=1.0.0'
                    echo 'Building the application...'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'dotnet test --no-restore --configuration Release'
                    echo 'Testing the application...'
                }
            }
        }

        stage('Dockerize') {
            steps {
                script {
                    def branchName = getBranchName()
                    def portMapping = getPort(branchName)
                    
                    sh """
                        docker build -t ${env.DOCKER_IMAGE}:${branchName} .
                        docker stop ${env.DOCKER_IMAGE}-${branchName} || true
                        docker rm ${env.DOCKER_IMAGE}-${branchName} || true
                        docker run -d \\
                            -p ${portMapping} \\
                            --name ${env.DOCKER_IMAGE}-${branchName} \\
                            ${env.DOCKER_IMAGE}:${branchName}
                    """
                    echo "Dockerized application running on port ${portMapping.split(':')[0]}"
                }
            }
        }
    }

    post {
        always {
            echo 'Build, Test, and Publish completed.'
        }
    }
}